# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170127_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
